services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql-sqli
    environment:
      MYSQL_ROOT_PASSWORD: root
